version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: iskanderrrr/foodgram_backend:latest
    expose:
      - 8000
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py load_ingredients ingredients.csv
        python manage.py collectstatic --noinput
        python manage.py loaddata data.json
        gunicorn --bind 0:8000 foodgram.wsgi
    volumes:
      - backend_static:/app/static/
      - media_value:/app/media/
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: iskanderrrr/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/usr/share/nginx/html/backend_static/:ro
      - media_value:/usr/share/nginx/html/media/:ro
    restart: always
    depends_on:
      - frontend

volumes:
  db:
  backend_static:
  media_value:
